"""empty message

Revision ID: 89b727d61ecd
Revises: a81f43fcb488
Create Date: 2019-06-29 15:10:50.316335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b727d61ecd'
down_revision = 'a81f43fcb488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'frequency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
