"""empty message

Revision ID: f29b7efdf870
Revises: 89b727d61ecd
Create Date: 2019-06-29 18:51:22.139193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f29b7efdf870'
down_revision = '89b727d61ecd'
branch_labels = None
depends_on = None


def upgrade():
    frequency = postgresql.ENUM('Daily', 'EveryOtherDay', 'Weekly', name='frequency')
    frequency.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('frequency', sa.Enum('Daily', 'EveryOtherDay', 'Weekly', name='frequency'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'frequency')
    # ### end Alembic commands ###

    frequency = postgresql.ENUM('Daily', 'EveryOtherDay', 'Weekly', name='frequency')
    frequency.drop(op.get_bind())
